# Hungarian translation of mintbackup.
# Copyright (C) 2013-2014 Free Software Foundation, Inc.
# This file is distributed under the same license as the mintbackup package.
# KAMI <kami911@gmail.com>, 2013-2014.
#
msgid ""
msgstr ""
"Project-Id-Version: mintbackup\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2016-04-22 13:59+0100\n"
"PO-Revision-Date: 2016-07-04 18:12+0000\n"
"Last-Translator: KAMI <kami911@gmail.com>\n"
"Language-Team: Hungarian\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2016-10-24 14:38+0000\n"
"X-Generator: Launchpad (build 18246)\n"
"Language: hu\n"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:111
#: usr/lib/linuxmint/mintbackup/mintbackup.py:252
#: usr/lib/linuxmint/mintbackup/mintbackup.py:449
#: usr/lib/linuxmint/mintbackup/mintbackup.py:467
#: usr/lib/linuxmint/mintbackup/mintbackup.py:533
#: usr/lib/linuxmint/mintbackup/mintbackup.py:536
#: usr/lib/linuxmint/mintbackup/mintbackup.py:588
#: usr/lib/linuxmint/mintbackup/mintbackup.py:591
#: usr/lib/linuxmint/mintbackup/mintbackup.py:611
#: usr/lib/linuxmint/mintbackup/mintbackup.py:634
#: usr/lib/linuxmint/mintbackup/mintbackup.py:641
#: usr/lib/linuxmint/mintbackup/mintbackup.py:1498
#: usr/lib/linuxmint/mintbackup/mintbackup.py:1596
#: usr/lib/linuxmint/mintbackup/mintbackup.py:1604
#: usr/lib/linuxmint/mintbackup/mintbackup.py:1656 generate_desktop_files.py:26
#: generate_desktop_files.py:41 generate_desktop_files.py:56
msgid "Backup Tool"
msgstr "Mentéskezelő"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:169
msgid "Preserve structure"
msgstr "Struktúra megőrzése"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:171
msgid ".tar file"
msgstr ".tar fájl"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:172
msgid ".tar.bz2 file"
msgstr ".tar.bz2 fájl"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:173
msgid ".tar.gz file"
msgstr ".tar.gz fájl"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:179
msgid "Never"
msgstr "Soha"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:180
msgid "Size mismatch"
msgstr "Méreteltérés"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:181
msgid "Modification time mismatch"
msgstr "Módosítási idő eltérés"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:182
msgid "Checksum mismatch"
msgstr "Hibás ellenőrzőösszeg"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:183
msgid "Always"
msgstr "Mindig"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:205
msgid "Excluded paths"
msgstr "Kihagyott útvonalak"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:215
msgid "Type"
msgstr "Típus"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:219
msgid "Detail"
msgstr "Részletek"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:225
#: usr/lib/linuxmint/mintbackup/mintbackup.py:234
msgid "Path"
msgstr "Útvonal"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:228
#: usr/lib/linuxmint/mintbackup/mintbackup.py:237
msgid "Error"
msgstr "Hiba"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:269
msgid "Store?"
msgstr "Elmentsük?"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:272
#: usr/lib/linuxmint/mintbackup/mintbackup.py:285
msgid "Name"
msgstr "Név"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:282
msgid "Install"
msgstr "Telepítés"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:290
msgid "Backup or Restore"
msgstr "Biztonsági mentés vagy visszaállítás"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:291
msgid "Choose from the following options"
msgstr "Válasszon az alábbiak közül"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:293
#: usr/lib/linuxmint/mintbackup/mintbackup.py:309
#: usr/lib/linuxmint/mintbackup/mintbackup.py:323
#: usr/lib/linuxmint/mintbackup/mintbackup.py:330
#: usr/lib/linuxmint/mintbackup/mintbackup.py:334
#: usr/lib/linuxmint/mintbackup/mintbackup.py:339
msgid "Backup files"
msgstr "Fájlok biztonsági mentése"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:294
#: usr/lib/linuxmint/mintbackup/mintbackup.py:343
#: usr/lib/linuxmint/mintbackup/mintbackup.py:353
#: usr/lib/linuxmint/mintbackup/mintbackup.py:359
#: usr/lib/linuxmint/mintbackup/mintbackup.py:364
msgid "Restore files"
msgstr "Fájlok visszaállítása"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:295
#: usr/lib/linuxmint/mintbackup/mintbackup.py:368
#: usr/lib/linuxmint/mintbackup/mintbackup.py:373
#: usr/lib/linuxmint/mintbackup/mintbackup.py:379
#: usr/lib/linuxmint/mintbackup/mintbackup.py:384
msgid "Backup software selection"
msgstr "Szoftverválaszték mentése"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:296
#: usr/lib/linuxmint/mintbackup/mintbackup.py:388
#: usr/lib/linuxmint/mintbackup/mintbackup.py:393
#: usr/lib/linuxmint/mintbackup/mintbackup.py:400
msgid "Restore software selection"
msgstr "Szoftverválaszték visszaállítása"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:298
msgid "Make a backup of your files"
msgstr "Saját fájlok biztonsági mentése"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:299
msgid "Save the list of installed applications"
msgstr "Telepített alkalmazások listájának mentése"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:300
msgid "Restore a previous backup"
msgstr "Korábbi mentés visszaállítása"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:301
msgid "Restore previously installed applications"
msgstr "Korábban telepített alkalmazások visszaállítása"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:310
msgid "Please select a source and a destination for your backup"
msgstr "Válassza ki a biztonsági mentés forrását és célját"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:311
#: usr/lib/linuxmint/mintbackup/mintbackup.py:347
#: usr/lib/linuxmint/mintbackup/mintbackup.py:355
msgid "Source:"
msgstr "Forrás:"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:312
#: usr/lib/linuxmint/mintbackup/mintbackup.py:348
msgid "Destination:"
msgstr "Cél:"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:313
#: usr/lib/linuxmint/mintbackup/mintbackup.py:349
msgid "Advanced options"
msgstr "Haladó beállítások"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:314
#: usr/lib/linuxmint/mintbackup/mintbackup.py:356
msgid "Description:"
msgstr "Leírás:"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:315
msgid "Output:"
msgstr "Kimenet:"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:316
#: usr/lib/linuxmint/mintbackup/mintbackup.py:350
msgid "Overwrite:"
msgstr "Felülírás:"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:317
msgid "Confirm integrity"
msgstr "Integritás megőrzése"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:318
msgid "Follow symlinks"
msgstr "Szimbolikus linkek követése"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:319
msgid "Preserve permissions"
msgstr "Jogosultságok megőrzése"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:320
msgid "Preserve timestamps"
msgstr "Időbélyegek megőrzése"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:324
msgid "Please select any files or directories you want to exclude"
msgstr "Válassza ki a kihagyni kívánt fájlokat vagy mappákat"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:325
msgid "Exclude files"
msgstr "Kihagyandó fájlok"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:326
msgid "Exclude directories"
msgstr "Kihagyandó mappák"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:327
msgid "Remove"
msgstr "Eltávolítás"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:331
msgid "Please review the information below before starting the backup"
msgstr "Nézze át a beállításokat a mentés megkezdése előtt"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:335
msgid "Please wait while your files are being backed up"
msgstr "Kérem várjon, amíg a mentés befejeződik"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:336
#: usr/lib/linuxmint/mintbackup/mintbackup.py:381
msgid "Backing up:"
msgstr "Biztonsági mentés:"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:340
#: usr/lib/linuxmint/mintbackup/mintbackup.py:385
msgid "The backup is now finished"
msgstr "A biztonsági mentés befejeződött"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:344
msgid ""
"Please choose the type of backup to restore, its location and a destination"
msgstr "Válassza ki a visszaállítandó mentés típusát, helyét és célját"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:345
msgid "Archive"
msgstr "Archívum"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:346
msgid "Directory"
msgstr "Mappa"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:354
msgid "Please review the information below"
msgstr "Nézze át az alábbiakat"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:360
msgid "Please wait while your files are being restored"
msgstr "Kérem várjon, amíg a visszaállítás befejeződik"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:361
msgid "Restoring:"
msgstr "Visszaállítás:"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:365
msgid "The restoration of the files is now finished"
msgstr "A fájlok visszaállítása befejeződött"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:369
msgid "Please choose a destination"
msgstr "Válassza ki a célhelyet"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:370
#: usr/lib/linuxmint/mintbackup/mintbackup.py:552
msgid "Destination"
msgstr "Cél"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:374
msgid "The list below shows the packages you added to Linux Mint"
msgstr ""
"Az alábbi listán azokat a csomagokat találja, amelyeket Ön adott a Linux "
"Mint-hez"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:375
#: usr/lib/linuxmint/mintbackup/mintbackup.py:395
msgid "Select all"
msgstr "Összes kijelölése"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:376
#: usr/lib/linuxmint/mintbackup/mintbackup.py:396
msgid "Deselect all"
msgstr "Kijelölés megszüntetése"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:380
msgid "Please wait while your software selection is being backed up"
msgstr "Kérem várjon, amíg a szoftverkészlet mentésre kerül"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:389
msgid "Please select a saved software selection"
msgstr "Válasszon egy elmentett szoftverkészletet"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:390
msgid "Software selection:"
msgstr "Szoftverkészlet:"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:394
msgid "Select the packages you want to install"
msgstr "Válassza ki a telepíteni kívánt csomagokat"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:397
msgid "Refresh"
msgstr "Frissítés"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:401
msgid "The restoration is now finished"
msgstr "A visszaállítás befejeződött"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:402
msgid "Your package selection was restored successfully"
msgstr "A szoftverválaszték sikeresen visszaállítva."

#: usr/lib/linuxmint/mintbackup/mintbackup.py:458
#: usr/lib/linuxmint/mintbackup/mintbackup.py:476
msgid "Invalid path"
msgstr "Érvénytelen útvonal"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:458
#: usr/lib/linuxmint/mintbackup/mintbackup.py:476
#, python-format
msgid "%s is not located within your source directory. Not added."
msgstr "%s nem található a forrásmappában. Nem lett hozzáadva."

#: usr/lib/linuxmint/mintbackup/mintbackup.py:533
msgid "Please choose directories for the source and the destination"
msgstr "Válassza ki a biztonsági mentés forrás- és célmappáit"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:536
msgid ""
"Please choose different directories for the source and the destination"
msgstr "Válasszon különböző mappát a forrásnak és a célnak"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:551
msgid "Source"
msgstr "Forrás"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:554
msgid "Description"
msgstr "Leírás"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:558
msgid "Compression"
msgstr "Tömörítés"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:562
msgid "Overwrite destination files"
msgstr "Létező fájlok felülírása"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:565
msgid "Exclude"
msgstr "Kihagyás"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:588
msgid "Please choose a file to restore from"
msgstr "Válassza ki a fájlt, amelyből vissza szeretne állítani"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:591
#: usr/lib/linuxmint/mintbackup/mintbackup.py:611
msgid "Please choose a destination directory"
msgstr "Válassza ki a célmappát"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:634
msgid "No packages need to be installed at this time"
msgstr "Nem került telepítése csomag"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:641
msgid "Please select one or more packages to install"
msgstr "Válassza ki a telepítendő csomagokat"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:709
#: usr/lib/linuxmint/mintbackup/mintbackup.py:710
#: usr/lib/linuxmint/mintbackup/mintbackup.py:1204
#: usr/lib/linuxmint/mintbackup/mintbackup.py:1206
#: usr/lib/linuxmint/mintbackup/mintbackup.py:1513
#: usr/lib/linuxmint/mintbackup/mintbackup.py:1514
msgid "Calculating..."
msgstr "Számítás…"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:759
#: usr/lib/linuxmint/mintbackup/mintbackup.py:799
msgid "Skipping broken link"
msgstr "Törött linkek kihagyása"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:760
msgid "Broken link"
msgstr "Törött link"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:763
#: usr/lib/linuxmint/mintbackup/mintbackup.py:803
msgid "Skipping link"
msgstr "Link kihagyása"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:827
#: usr/lib/linuxmint/mintbackup/mintbackup.py:836
#: usr/lib/linuxmint/mintbackup/mintbackup.py:845
#: usr/lib/linuxmint/mintbackup/mintbackup.py:1265
#: usr/lib/linuxmint/mintbackup/mintbackup.py:1276
#: usr/lib/linuxmint/mintbackup/mintbackup.py:1289
#: usr/lib/linuxmint/mintbackup/mintbackup.py:1354
#: usr/lib/linuxmint/mintbackup/mintbackup.py:1363
#: usr/lib/linuxmint/mintbackup/mintbackup.py:1373
msgid "Skipping identical file"
msgstr "Azonos fájl kihagyása"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:867
#, python-format
msgid ""
"Warning: Some files were not saved, copied: %(current_file)d files out of "
"%(total)d total"
msgstr ""
"Figyelmeztetés: Néhány fájl nem lett mentve, %(total)d fájlból "
"%(current_file)d fájl lett átmásolva"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:871
msgid "An error occurred during the backup"
msgstr "Hiba lépett fel a mentés készítése közben"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:881
#: usr/lib/linuxmint/mintbackup/mintbackup.py:1559
msgid "The backup was aborted"
msgstr "Mentés megszakítva"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:889
msgid "The backup completed successfully"
msgstr "A mentés sikeresen befejeződött"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:980
msgid "Checksum Mismatch:"
msgstr "Ellenőrzőösszeg hiba:"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:981
msgid "Checksum Mismatch"
msgstr "Ellenőrzőösszeg hiba"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:1033
#: usr/lib/linuxmint/mintbackup/mintbackup.py:1035
#: usr/lib/linuxmint/mintbackup/mintbackup.py:1064
msgid "Calculating checksum"
msgstr "Ellenőrzőösszeg számítása"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:1110
#: usr/lib/linuxmint/mintbackup/mintbackup.py:1134
msgid "(Not created with the Backup Tool)"
msgstr "(nem a Mentéskezelővel készült)"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:1397
#, python-format
msgid ""
"Warning: Some files were not restored, copied: %(current_file)d files out of "
"%(total)d total"
msgstr ""
"Figyelmeztetés: Néhány fájl nem lett visszaállítva, %(total)d fájlból "
"%(current_file)d fájl lett átmásolva"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:1400
msgid "An error occurred during the restoration"
msgstr "Hiba lépett fel visszaállítás közben"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:1411
msgid "The restoration was aborted"
msgstr "Visszaállítás megszakítva"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:1419
msgid "The restoration completed successfully"
msgstr "A visszaállítás sikeresen befejeződött"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:1550
msgid "An error occurred during the backup:"
msgstr "A következő hiba lépett fel a mentés során:"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:1567
msgid "Your software selection was backed up successfully"
msgstr "A szoftverválaszték sikeresen elmentve."

#: usr/lib/linuxmint/mintbackup/mintbackup.py:1596
msgid "The specified file is not a valid software selection"
msgstr "A megadott fájl nem érvényes szoftverkészlet"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:1604
#: usr/lib/linuxmint/mintbackup/mintbackup.py:1656
msgid "An error occurred while accessing the file"
msgstr "Hiba történt a fájl elérése közben"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:1649
msgid "Could not locate the package"
msgstr "A csomag nem található"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:1681
msgid "Please wait, this can take some time"
msgstr "Kis türelmet, ez eltarthat egy ideig"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:1683
msgid "The installation is complete"
msgstr "A telepítés kész"

#: generate_desktop_files.py:26 generate_desktop_files.py:41
#: generate_desktop_files.py:56
msgid "Make a backup of your home directory"
msgstr "Mentés készítése a saját mappáról"

#~ msgid "Archiving your home directory..."
#~ msgstr "A Saját mappa archiválása..."

#~ msgid "Backup successful"
#~ msgstr "A mentés sikerült"

#~ msgid "Backup failed"
#~ msgstr "A mentés nem sikerült"

#~ msgid "Extracting the content of the backup into your home directory..."
#~ msgstr "A mentés tartalmának kicsomagolása a Saját mappába..."

#~ msgid "Copying the backup file into your home directory..."
#~ msgstr "A mentésfájl másolása a Saját mappába..."

#~ msgid "Restoration successful"
#~ msgstr "A visszaállítás sikerült"

#~ msgid "Cleaning up..."
#~ msgstr "Takarítás..."

#~ msgid "Your backup was successfully restored"
#~ msgstr "A mentés sikeresen visszaállítva"

#~ msgid "Your home directory was successfully backed-up into"
#~ msgstr "A Saját mappa sikeresen mentve a következő fájlba:"

#~ msgid "Backup"
#~ msgstr "Mentés"

#~ msgid "Restoration failed"
#~ msgstr "A visszaállítás nem sikerült"

#~ msgid "An error occurred while restoring the backup archive:"
#~ msgstr "A következő hiba lépett fel a visszaállítás során:"

#~ msgid "Read error"
#~ msgstr "Olvasási hiba"

#~ msgid "Restore your personal data from this backup"
#~ msgstr "Személyes adatainak visszaállítása ebből a mentésből"

#~ msgid "<big><b>Load data into your home directory</b></big>"
#~ msgstr "<big><b>Adatok visszatöltése a Saját mappába</b></big>"

#~ msgid "is not located within your home directory. Not added."
#~ msgstr "nem a Saját mappában található. Nem adható meg."

#~ msgid "Included hidden directories"
#~ msgstr "Mentendő rejtett fájlok és mappák"

#~ msgid "Included"
#~ msgstr "Mentés"

#~ msgid "Restore"
#~ msgstr "Visszaállítás"

#~ msgid "Overwrite existing files"
#~ msgstr "Létező fájlok felülírása"

#~ msgid "View content"
#~ msgstr "Tartalom megtekintése"

#~ msgid "Exclude folders"
#~ msgstr "Mappák kihagyása"

#~ msgid "Excluded Files and Directories"
#~ msgstr "A mentésből kihagyott fájlok és mappák"

#~ msgid "Hidden paths"
#~ msgstr "Rejtett elemek"

#~ msgid "Opening the backup archive..."
#~ msgstr "A mentési archívum megnyitása..."

#~ msgid "An error occurred while opening the backup:"
#~ msgstr "A következő hiba lépett fel a mentés megnyitása során:"
